# Unbind prefix to Control + b
unbind C-b
# Prefix to Control + Space
set -g prefix C-space
bind C-Space send-prefix

# Split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch between two most recently used windows
bind Space last-window

# Switch between two most recently used sessions
bind ^ switch-client -l

set -g mouse on

# TPM path (nixos specific?)
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$DOTFILES_CONFIG/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/vim-tmux'
set -g @plugin 'tmux-plugins/vim-tmux-focus-events'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g history-limit 25000

# for neovim
set -sg escape-time 10
set-option -g focus-events on

# vi for copy mode
setw -g mode-keys vi
set -g status-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# status bar
set -g status-right "#(pomo)"
set -g status-style "fg=#665c54"
set -g status-left-style "fg=#928374"

set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left ""

# rename panes to current working directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# disable status
# set -g status off
# set -g status on

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# reload configuration
bind-key -r r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded tmux conf"

# term colors, these are the correct ones according to neovim checkhealth
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

bind -T root F12  \
  set prefix None \;\
  set prefix2 None \;\
  set key-table off \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u prefix2 \;\
  set -u key-table \;\
  refresh-client -S

run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
