alias hl="cd $LAB"
alias hp="cd $HOME/code/homepage"
alias lrn="cd $HOME/code/learning"
alias sb="cd $HOME/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/sb"
alias write="cd $HOME/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/writing/writing"
